name: Hourly BTC Data Collection

on:
  schedule:
    - cron: '0 * * * *'  # Каждый час в 00 минут
  workflow_dispatch:

jobs:
  collect-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          pip install requests pandas
      - name: Run script
        run: python main.py
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update data for ${{ github.event.schedule || github.run_id }}"
